### ISSUE TITLE
I am not able to run the jarvis.py

### ISSUE THREAD

**Issue by pritam5305** [GauravSingh9356/J.A.R.V.I.S#15]
ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (C:\Users\PRITAM MOHAPATRA\anaconda3\lib\site-packages\comtypes\gen\__init__.py)

I am getting this error. can anyone please help me with it?

I have tried installing "pip install --upgrade --force-reinstall --user pyttsx3" but still not able to run it.

My operating system is windows10-Home-X64 bit

**Comment by pritam5305** [comment]
File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]

  File "C:\Users\PRITAM MOHAPATRA\anaconda3\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()

KeyError: None


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    from comtypes.gen import SpeechLib  # comtypes

ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\gen\__init__.py)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\PRITAM MOHAPATRA\anaconda3\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]

KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>, <class 'ctypes.wintypes.LP_c_long'>), 0)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\PRITAM MOHAPATRA\Downloads\untitled0.py", line 22, in <module>
    engine = pyttsx3.init()

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)

  File "C:\Users\PRITAM MOHAPATRA\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\pyttsx3\drivers\sapi5.py", line 6, in <module>
    engine = comtypes.client.CreateObject("SAPI.SpVoice")

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\gen\_C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4.py", line 1676, in <module>
    ( ['out', 'retval'], POINTER(VARIANT), 'NewPosition' )),

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)

  File "C:\Users\PRITAM MOHAPATRA\AppData\Roaming\Python\Python37\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)

  File "C:\Users\PRITAM MOHAPATRA\anaconda3\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):

TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

**Comment by GauravSingh9356** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/
go there and check for pyaudio, based on ur system requirements install the desired whl file.

**Comment by pritam5305** [comment]
Hi Gaurav,

I tried install pyaudio whl files and its saying :

"Requirement already satisfied: PyAudio==0.2.11 from file:///C:/Users/public/Downloads/PyAudio-0.2.11-py2.py3-none-any.whl in c:\users\pritam mohapatra\anaconda3\lib\site-packages (0.2.11)"


But still i am facing the same issue.

**Comment by pritam5305** [comment]
Even Tried Installing comtypes : 

pip install C:\Users\public\Downloads\comtypes-1.1.7-py3-none-any.whl


Requirement already satisfied: comtypes==1.1.7 from file:///C:/Users/public/Downloads/comtypes-1.1.7-py3-none-any.whl in c:\users\pritam mohapatra\appdata\roaming\python\python37\site-packages (1.1.7)

**Comment by GauravSingh9356** [comment]
Can you give a try with python 3.8 version by installing it separately apart from anaconda's version of python? I have done it the same. I have anaconda but done with the latest python 3.8

**Comment by pritam5305** [comment]
Hi Gaurav,

if i am trying to run it in pythin 3.8 its giving an error :

Traceback (most recent call last):
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PRITAM MOHAPATRA\Downloads\Jarvis.py", line 76, in <module>
    query = takeCommand().lower()
  File "C:\Users\PRITAM MOHAPATRA\Downloads\Jarvis.py", line 27, in takeCommand
    with sr.Microphone() as source:
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation




If i am trying to install pyaudio then its giving the below error : 


  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-wheel-e0d771ry'
       cwd: C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-install-gr7y4ucj\pyaudio\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying src\pyaudio.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_portaudio' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-record-01q3zypl\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pyaudio'
         cwd: C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-install-gr7y4ucj\pyaudio\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying src\pyaudio.py -> build\lib.win-amd64-3.8
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-gr7y4ucj\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-record-01q3zypl\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pyaudio' Check the logs for full command output.


i have tried installing microsoft visual C++ but still getting this error!

**Comment by GauravSingh9356** [comment]
Are you installing pyaudio with whl file, do it with whl file downloaded only. I got the same error while doing by pip install pyaudio.

**Comment by pritam5305** [comment]
yeah i have tried both even after using installing using whl file 


after saying "'I am JARVIS. Please tell me how can I help you SIR?'


i am getting this error :

============ RESTART: C:\Users\PRITAM MOHAPATRA\Downloads\Jarvis.py ============
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ModuleNotFoundError: No module named '_portaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PRITAM MOHAPATRA\Downloads\Jarvis.py", line 76, in <module>
    query = takeCommand().lower()
  File "C:\Users\PRITAM MOHAPATRA\Downloads\Jarvis.py", line 27, in takeCommand
    with sr.Microphone() as source:
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
>>>

**Comment by pritam5305** [comment]
so now i have installed microsoft visual  C++ 2019 now the error showing is :


    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-fh6hmjsf\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-fh6hmjsf\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-record-a61re8tx\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pyaudio'
         cwd: C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-install-fh6hmjsf\pyaudio\
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying src\pyaudio.py -> build\lib.win-amd64-3.8
    running build_ext
    building '_portaudio' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMS_WIN64=1 "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/_portaudiomodule.c /Fobuild\temp.win-amd64-3.8\Release\src/_portaudiomodule.obj
    _portaudiomodule.c
    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\include\pyconfig.h(117): warning C4005: 'MS_WIN64': macro redefinition
    src/_portaudiomodule.c: note: see previous definition of 'MS_WIN64'
    src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of pyaudio
  Moving to c:\users\pritam mohapatra\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages\__pycache__\pyaudio.cpython-38.pyc
   from C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-uninstall-v03j60ml\pyaudio.cpython-38.pyc
  Moving to c:\users\pritam mohapatra\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages\_portaudio.cp39-win_amd64.pyd
   from C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-uninstall-d9gnjhbe\_portaudio.cp39-win_amd64.pyd
  Moving to c:\users\pritam mohapatra\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages\pyaudio-0.2.11.dist-info\
   from C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\~yaudio-0.2.11.dist-info
  Moving to c:\users\pritam mohapatra\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages\pyaudio.py
   from C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-uninstall-d9gnjhbe\pyaudio.py
ERROR: Command errored out with exit status 1: 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-fh6hmjsf\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRITAM MOHAPATRA\\AppData\\Local\\Temp\\pip-install-fh6hmjsf\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Temp\pip-record-a61re8tx\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\PRITAM MOHAPATRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pyaudio' Check the logs for full command output.

**Comment by GauravSingh9356** [comment]
Uninstall pyaudio using pip and then install portaudio. After this, again install pyaudio.

**Comment by pritam5305** [comment]
Yeah it worked gaurav.

Thanks a lot..

**Comment by GauravSingh9356** [comment]
Extremely happy that it worked.
Cheers!
